on:
  push:
    branches:
      - main
      - devl
  pull_request:
    branches:
      - main
      - devl


name: test

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')" 
    runs-on: ubuntu-latest
   
    steps:
      - name: test env var
        if: "!contains(github.event.head_commit.message, '[skip-tests]')"
        run: |
          echo "skipping tests"
          
      - name: test env var2
        if: "contains(github.event.head_commit.message, '[skip-tests]')"
        run: |
          echo ${{github.event.head_commit.message}}
          echo "not skipping tests"

