on:
  push:
    branches:
      - main
      - devl
  pull_request:
    branches:
      - main
      - devl


name: test

jobs:
  get_message:
    runs-on: ubuntu-latest
    outputs:
      commitmsg: ${{ steps.getmsg.outputs.msg }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
    
      - name: Set tags env variables
        id: getmsg
        run: |
          # Get your last commit message, not the merge commit.
          msg=$(git log -1 --no-merges --pretty=%B)
          echo "msg=$(git log -1 --no-merges --pretty=%B)" >> "$GITHUB_OUTPUT"
          echo "commit message: $msg"
        
  test:
    if: "!contains(needs.get_message.outputs.commitmsg, '[skip-ci]')" 
    needs: get_message
    runs-on: ubuntu-latest

    steps:
      - name: test env var
        if: "!contains(needs.get_message.outputs.commitmsg, '[skip-tests]')"
        run: |
          echo "${{ needs.get_message.outputs.commitmsg }}"
          echo "not skipping tests"
          
      - name: test env var2
        if: "contains(needs.get_message.outputs.commitmsg, '[skip-tests]')"
        run: |
          echo "${{ needs.get_message.outputs.commitmsg }}"
          echo "skipping tests"

