## blip

on:
  push:
    branches:
      - main
      - devl
  pull_request:
    branches:
      - main
      - devl


name: test

jobs:
  get_message:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set tags env variables
        run: |
          # Get your last commit message, not the merge commit.
          text=$(git log -1 --no-merges --pretty=%B)
          echo "commit message: $text"
        
  test:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')" 
    runs-on: ubuntu-latest
   
    steps:
      - name: test env var
        if: "!contains(github.event.head_commit.message, '[skip-tests]')"
        run: |
          echo "not skipping tests"
          
      - name: test env var2
        if: "contains(github.event.head_commit.message, '[skip-tests]')"
        run: |
          echo ${{github.event.head_commit.message}}
          echo "skipping tests"

